name: 'Render Deploy'
description: 'Deploys a Render app and waits for deployment to finish'
author: 'Half Dome Labs LLC'

inputs:
  service-id:
    description: 'The ID of the Render service to deploy'
    required: true
  render-token:
    description: 'The Render API token'
    required: true
  wait-for-deploy:
    description: 'Whether to wait for the deployment to finish'
    required: false
    default: 'true'
  timeout:
    description: 'The maximum time to wait for the deployment to finish (ms)'
    required: false
    default: '1200000'

outputs:
  deploy-id:
    description: 'The ID of the deployment'

runs:
  using: node20
  main: dist/index.js
