name: 'Render Deploy'
description: 'Deploys a Render app and waits for deployment to finish'
author: 'Half Dome Labs LLC'

inputs:
  service-id:
    description: 'The ID of the Render service to deploy'
    required: true
  render-token:
    description: 'The Render API token'
    required: true
  wait-for-deploy:
    description: 'Whether to wait for the deployment to finish'
    required: false
    default: 'true'
  timeout-minutes:
    description: 'The maximum time to wait for the deployment to finish (minutes)'
    required: false
    default: '20'
  image-url:
    description: 'The image URL to deploy (for image-based services)'
    required: false
  commit-id:
    description: 'The specific commit ID to deploy'
    required: false

outputs:
  deploy-id:
    description: 'The ID of the deployment'

runs:
  using: node24
  main: dist/index.js
