blockExoticSubdeps: true

linkWorkspacePackages: true

minimumReleaseAge: 2880 # 2 days

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 43800 # 1 month

publishBranch: main

savePrefix: ''

saveWorkspaceProtocol: rolling

onlyBuiltDependencies:
  - esbuild
