name: 'Setup pnpm'
description: 'Sets up pnpm'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # 3.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: 'pnpm'
    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
