name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Check Format
        id: pnpm-format-check
        run: pnpm format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm lint
