name: Lint and Typecheck

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint-and-typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Check Format
        id: pnpm-format-check
        run: pnpm format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm lint

      - name: Typescript
        id: pnpm-tsc
        run: pnpm tsc --noEmit
