name: Lint and Typecheck

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint-and-typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Check Format
        id: prettier
        run: pnpm prettier:check

      - name: Lint
        id: lint
        run: pnpm lint

      - name: Typescript
        id: typecheck
        run: pnpm typecheck

      - name: Test
        id: test
        run: pnpm test
